spring.application.name=PromotionManagement

server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/promotions
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.app.jwtSecret=7fpKwXseAdG3bU51Pp2KD2IqV9K5jLQnZhXr+M47hFkFyUIM9kLd4cNOjNlPUyI8Fmf2JgRZRLsbmyZ8WJwUyQ==
spring.app.jwtExpirationMs=50000000

